import React from 'react';
import { useNavigate } from 'react-router-dom';
import { FilterBar } from '../components/common/FilterBar';
import { RiskBadge } from '../components/common/RiskBadge';
import { alerts } from '../data/mockData';

export const Alerts: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="p-6 space-y-4">
      {/* Page Header */}
      <div>
        <h2 className="text-base font-bold text-[#17202A] tracking-tight font-mono">Alerts Management</h2>
        <p className="text-xs text-slate-500 mt-0.5">
          Operational alert queue generated by GraphSAGE fraud ring risk triggers.
        </p>
      </div>

      {/* Filter Bar */}
      <FilterBar />

      {/* Alerts Data Table */}
      <div className="bg-white border border-[#D9DDE3] rounded overflow-hidden">
        <div className="overflow-x-auto">
          <table>
            <thead>
              <tr>
                <th>Alert ID</th>
                <th>Ring ID</th>
                <th>Risk Score</th>
                <th>Severity</th>
                <th>Detected</th>
                <th>Financial Exposure</th>
                <th>Status</th>
                <th>Assigned Analyst</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {alerts.map((alert) => (
                <tr
                  key={alert.id}
                  onClick={() => navigate(`/rings/${alert.ringId}`)}
                  className="hover:bg-slate-50 cursor-pointer"
                >
                  <td className="font-mono font-bold text-[#2457A6]">{alert.id}</td>
                  <td className="font-mono font-bold text-slate-700">{alert.ringId}</td>
                  <td className="font-mono font-bold">
                    <span className={alert.riskScore >= 70 ? 'text-red-700' : 'text-amber-800'}>
                      {alert.riskScore.toFixed(1)}%
                    </span>
                  </td>
                  <td>
                    <RiskBadge status={alert.severity} showScore={false} />
                  </td>
                  <td className="font-mono text-slate-500 text-xs">{alert.detected}</td>
                  <td className="font-mono font-semibold text-[#17202A]">
                    ₹{(alert.exposure / 100000).toFixed(2)}L
                  </td>
                  <td>
                    <span className={`px-2 py-0.5 text-[10px] font-mono font-bold uppercase rounded border ${
                      alert.status === 'new' ? 'bg-red-100 text-red-800 border-red-300' :
                      alert.status === 'investigating' ? 'bg-amber-100 text-amber-900 border-amber-300' :
                      alert.status === 'escalated' ? 'bg-purple-100 text-purple-900 border-purple-300' :
                      'bg-slate-100 text-slate-700 border-slate-300'
                    }`}>
                      {alert.status.replace('_', ' ')}
                    </span>
                  </td>
                  <td className="font-mono text-slate-700 text-xs">{alert.assignedTo}</td>
                  <td>
                    <button className="px-2 py-1 bg-slate-100 border border-slate-300 rounded text-xs font-mono font-semibold hover:bg-slate-200">
                      Review
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
